//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИСС_Автопрокат.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int ID_Contract { get; set; }
        public int CodeProduct_Contract { get; set; }
        public int CodeClient_Contract { get; set; }
        public string Date_Contract { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Product Product { get; set; }
    }
}
