//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИСС_Автопрокат.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts_perf
    {
        public int ID_Contract { get; set; }
        public string Name_Product { get; set; }
        public decimal Price_Product { get; set; }
        public int ID_Client { get; set; }
        public string FullName_Client { get; set; }
        public System.DateTime Date_Contract { get; set; }
    }
}
