//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИСС_Автопрокат.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturers
    {
        public int ID_Manufacturer { get; set; }
        public string Name_Manufacturer { get; set; }
        public string Country_Manufacturer { get; set; }
        public string City_Manufacturer { get; set; }
        public string Street_Manufacturer { get; set; }
        public int HouseNumber_Manufacturer { get; set; }
        public int CodeProduct_Manufacturer { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
